services:
  registry:
    image: hashicorp/consul:latest
    restart: always
    container_name: registry
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5

  catalog-data:
    image: mongo:8.0.6
    container_name: catalog-data
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    restart: unless-stopped

  catalog-vector:
    image: qdrant/qdrant:dev
    container_name: catalog-vector
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/data/vector
    restart: unless-stopped

  catalog-gui:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: catalog-gui
    ports:
      - "27018:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@catalog-data:27017/
      - ME_CONFIG_BASICAUTH_ENABLED=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - catalog-data
    restart: unless-stopped

  catalog-gateway:
    build:
      context: ./db-gateway
      dockerfile: Dockerfile
    container_name: catalog-gateway
    ports:
      - "5000:5000"
    environment:
      - MONGO_USER=admin
      - MONGO_PASS=admin
      - MONGO_HOST=catalog-data
      - MONGO_PORT=27017
      - MONGO_DB=LADbridge
      - QDRANT_HOST=catalog-vector
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=services
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 5s
      retries: 40
    depends_on:
      - catalog-data
      - catalog-vector

  control-unit:
    build:
      context: ./control-unit
      dockerfile: Dockerfile
    container_name: control-unit
    ports:
      - "5500:5500"
    environment:
      - REGISTRY_URL=http://registry:8500
      - CATALOG_URL=http://catalog-gateway:5000
      - OLLAMA_API_URL=http://172.31.20.20:5000
    depends_on:
      registry:
        condition: service_healthy
  
  question-answering:
    build: 
      context: ./document-qa
      dockerfile: Dockerfile
    container_name: question-answering
    ports:
      - "5600:5600"
    environment:
      - SERVICE_ID="question-answering"
      - SERVICE_HOST=question-answering
      - SERVICE_PORT=5600
      - GATEWAY_HOST=catalog-gateway
      - GATEWAY_PORT=5000
      - CONSUL_HOST=registry
      - CONSUL_PORT=8500
      - OLLAMA_API_URL=http://172.31.20.20:5000
    
  document-autofiller:
    build: 
      context: ./document-autofiller
      dockerfile: Dockerfile
    container_name: document-autofiller
    ports:
      - "5700:5700"
    environment:
      - SERVICE_ID="document-autofiller"
      - SERVICE_HOST=document-autofiller
      - SERVICE_PORT=5700
      - GATEWAY_HOST=catalog-gateway
      - GATEWAY_PORT=5000
      - CONSUL_HOST=registry
      - CONSUL_PORT=8500
      - OLLAMA_API_URL=http://172.31.20.20:5000

volumes:
  mongo-data:
  qdrant-data:
